// Code generated by protoc-gen-go. DO NOT EDIT.
// source: price.proto

package price

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ItemID struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemID) Reset()         { *m = ItemID{} }
func (m *ItemID) String() string { return proto.CompactTextString(m) }
func (*ItemID) ProtoMessage()    {}
func (*ItemID) Descriptor() ([]byte, []int) {
	return fileDescriptor_94c214910ad4a3eb, []int{0}
}
func (m *ItemID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemID.Unmarshal(m, b)
}
func (m *ItemID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemID.Marshal(b, m, deterministic)
}
func (m *ItemID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemID.Merge(m, src)
}
func (m *ItemID) XXX_Size() int {
	return xxx_messageInfo_ItemID.Size(m)
}
func (m *ItemID) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemID.DiscardUnknown(m)
}

var xxx_messageInfo_ItemID proto.InternalMessageInfo

func (m *ItemID) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

type ItemPrice struct {
	Price                float32  `protobuf:"fixed32,1,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemPrice) Reset()         { *m = ItemPrice{} }
func (m *ItemPrice) String() string { return proto.CompactTextString(m) }
func (*ItemPrice) ProtoMessage()    {}
func (*ItemPrice) Descriptor() ([]byte, []int) {
	return fileDescriptor_94c214910ad4a3eb, []int{1}
}
func (m *ItemPrice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemPrice.Unmarshal(m, b)
}
func (m *ItemPrice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemPrice.Marshal(b, m, deterministic)
}
func (m *ItemPrice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemPrice.Merge(m, src)
}
func (m *ItemPrice) XXX_Size() int {
	return xxx_messageInfo_ItemPrice.Size(m)
}
func (m *ItemPrice) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemPrice.DiscardUnknown(m)
}

var xxx_messageInfo_ItemPrice proto.InternalMessageInfo

func (m *ItemPrice) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func init() {
	proto.RegisterType((*ItemID)(nil), "price.ItemID")
	proto.RegisterType((*ItemPrice)(nil), "price.ItemPrice")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PricerClient is the client API for Pricer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PricerClient interface {
	GetPrice(ctx context.Context, in *ItemID, opts ...grpc.CallOption) (*ItemPrice, error)
}

type pricerClient struct {
	cc *grpc.ClientConn
}

func NewPricerClient(cc *grpc.ClientConn) PricerClient {
	return &pricerClient{cc}
}

func (c *pricerClient) GetPrice(ctx context.Context, in *ItemID, opts ...grpc.CallOption) (*ItemPrice, error) {
	out := new(ItemPrice)
	err := c.cc.Invoke(ctx, "/price.Pricer/GetPrice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PricerServer is the server API for Pricer service.
type PricerServer interface {
	GetPrice(context.Context, *ItemID) (*ItemPrice, error)
}

func RegisterPricerServer(s *grpc.Server, srv PricerServer) {
	s.RegisterService(&_Pricer_serviceDesc, srv)
}

func _Pricer_GetPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ItemID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PricerServer).GetPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/price.Pricer/GetPrice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PricerServer).GetPrice(ctx, req.(*ItemID))
	}
	return interceptor(ctx, in, info, handler)
}

var _Pricer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "price.Pricer",
	HandlerType: (*PricerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPrice",
			Handler:    _Pricer_GetPrice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "price.proto",
}

func init() { proto.RegisterFile("price.proto", fileDescriptor_94c214910ad4a3eb) }

var fileDescriptor_94c214910ad4a3eb = []byte{
	// 122 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x28, 0xca, 0x4c,
	0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0x94, 0x24, 0xb8, 0xd8, 0x3c,
	0x4b, 0x52, 0x73, 0x3d, 0x5d, 0x84, 0xf8, 0xb8, 0x98, 0x3c, 0x5d, 0x24, 0x18, 0x15, 0x18, 0x35,
	0x98, 0x83, 0x98, 0x3c, 0x5d, 0x94, 0x14, 0xb9, 0x38, 0x41, 0x32, 0x01, 0x20, 0x65, 0x42, 0x22,
	0x5c, 0x10, 0xf5, 0x60, 0x79, 0xa6, 0x20, 0x08, 0xc7, 0xc8, 0x9c, 0x8b, 0x0d, 0x2c, 0x5d, 0x24,
	0xa4, 0xcb, 0xc5, 0xe1, 0x9e, 0x5a, 0x02, 0x51, 0xcb, 0xab, 0x07, 0xb1, 0x07, 0x62, 0xae, 0x94,
	0x00, 0x12, 0x17, 0xac, 0x40, 0x89, 0x21, 0x89, 0x0d, 0xec, 0x06, 0x63, 0x40, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xeb, 0x34, 0x0a, 0x9b, 0x92, 0x00, 0x00, 0x00,
}
