// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: price.proto

#include "price.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace price {
class ItemIDDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ItemID>
      _instance;
} _ItemID_default_instance_;
class ItemPriceDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ItemPrice>
      _instance;
} _ItemPrice_default_instance_;
}  // namespace price
namespace protobuf_price_2eproto {
static void InitDefaultsItemID() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::price::_ItemID_default_instance_;
    new (ptr) ::price::ItemID();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::price::ItemID::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ItemID =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsItemID}, {}};

static void InitDefaultsItemPrice() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::price::_ItemPrice_default_instance_;
    new (ptr) ::price::ItemPrice();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::price::ItemPrice::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ItemPrice =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsItemPrice}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_ItemID.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ItemPrice.base);
}

::google::protobuf::Metadata file_level_metadata[2];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::price::ItemID, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::price::ItemID, id_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::price::ItemPrice, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::price::ItemPrice, price_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::price::ItemID)},
  { 6, -1, sizeof(::price::ItemPrice)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::price::_ItemID_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::price::_ItemPrice_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "price.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\013price.proto\022\005price\"\024\n\006ItemID\022\n\n\002ID\030\001 \001"
      "(\003\"\032\n\tItemPrice\022\r\n\005price\030\001 \001(\00227\n\006Pricer"
      "\022-\n\010GetPrice\022\r.price.ItemID\032\020.price.Item"
      "Price\"\000b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 135);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "price.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_price_2eproto
namespace price {

// ===================================================================

void ItemID::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ItemID::kIDFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ItemID::ItemID()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_price_2eproto::scc_info_ItemID.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:price.ItemID)
}
ItemID::ItemID(const ItemID& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  id_ = from.id_;
  // @@protoc_insertion_point(copy_constructor:price.ItemID)
}

void ItemID::SharedCtor() {
  id_ = GOOGLE_LONGLONG(0);
}

ItemID::~ItemID() {
  // @@protoc_insertion_point(destructor:price.ItemID)
  SharedDtor();
}

void ItemID::SharedDtor() {
}

void ItemID::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ItemID::descriptor() {
  ::protobuf_price_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_price_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ItemID& ItemID::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_price_2eproto::scc_info_ItemID.base);
  return *internal_default_instance();
}


void ItemID::Clear() {
// @@protoc_insertion_point(message_clear_start:price.ItemID)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  id_ = GOOGLE_LONGLONG(0);
  _internal_metadata_.Clear();
}

bool ItemID::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:price.ItemID)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int64 ID = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:price.ItemID)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:price.ItemID)
  return false;
#undef DO_
}

void ItemID::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:price.ItemID)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 ID = 1;
  if (this->id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->id(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:price.ItemID)
}

::google::protobuf::uint8* ItemID::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:price.ItemID)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 ID = 1;
  if (this->id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(1, this->id(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:price.ItemID)
  return target;
}

size_t ItemID::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:price.ItemID)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // int64 ID = 1;
  if (this->id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->id());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ItemID::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:price.ItemID)
  GOOGLE_DCHECK_NE(&from, this);
  const ItemID* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ItemID>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:price.ItemID)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:price.ItemID)
    MergeFrom(*source);
  }
}

void ItemID::MergeFrom(const ItemID& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:price.ItemID)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.id() != 0) {
    set_id(from.id());
  }
}

void ItemID::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:price.ItemID)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ItemID::CopyFrom(const ItemID& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:price.ItemID)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ItemID::IsInitialized() const {
  return true;
}

void ItemID::Swap(ItemID* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ItemID::InternalSwap(ItemID* other) {
  using std::swap;
  swap(id_, other->id_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ItemID::GetMetadata() const {
  protobuf_price_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_price_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ItemPrice::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ItemPrice::kPriceFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ItemPrice::ItemPrice()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_price_2eproto::scc_info_ItemPrice.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:price.ItemPrice)
}
ItemPrice::ItemPrice(const ItemPrice& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  price_ = from.price_;
  // @@protoc_insertion_point(copy_constructor:price.ItemPrice)
}

void ItemPrice::SharedCtor() {
  price_ = 0;
}

ItemPrice::~ItemPrice() {
  // @@protoc_insertion_point(destructor:price.ItemPrice)
  SharedDtor();
}

void ItemPrice::SharedDtor() {
}

void ItemPrice::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ItemPrice::descriptor() {
  ::protobuf_price_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_price_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ItemPrice& ItemPrice::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_price_2eproto::scc_info_ItemPrice.base);
  return *internal_default_instance();
}


void ItemPrice::Clear() {
// @@protoc_insertion_point(message_clear_start:price.ItemPrice)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  price_ = 0;
  _internal_metadata_.Clear();
}

bool ItemPrice::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:price.ItemPrice)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // float price = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(13u /* 13 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &price_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:price.ItemPrice)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:price.ItemPrice)
  return false;
#undef DO_
}

void ItemPrice::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:price.ItemPrice)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // float price = 1;
  if (this->price() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(1, this->price(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:price.ItemPrice)
}

::google::protobuf::uint8* ItemPrice::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:price.ItemPrice)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // float price = 1;
  if (this->price() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(1, this->price(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:price.ItemPrice)
  return target;
}

size_t ItemPrice::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:price.ItemPrice)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // float price = 1;
  if (this->price() != 0) {
    total_size += 1 + 4;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ItemPrice::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:price.ItemPrice)
  GOOGLE_DCHECK_NE(&from, this);
  const ItemPrice* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ItemPrice>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:price.ItemPrice)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:price.ItemPrice)
    MergeFrom(*source);
  }
}

void ItemPrice::MergeFrom(const ItemPrice& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:price.ItemPrice)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.price() != 0) {
    set_price(from.price());
  }
}

void ItemPrice::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:price.ItemPrice)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ItemPrice::CopyFrom(const ItemPrice& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:price.ItemPrice)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ItemPrice::IsInitialized() const {
  return true;
}

void ItemPrice::Swap(ItemPrice* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ItemPrice::InternalSwap(ItemPrice* other) {
  using std::swap;
  swap(price_, other->price_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ItemPrice::GetMetadata() const {
  protobuf_price_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_price_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace price
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::price::ItemID* Arena::CreateMaybeMessage< ::price::ItemID >(Arena* arena) {
  return Arena::CreateInternal< ::price::ItemID >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::price::ItemPrice* Arena::CreateMaybeMessage< ::price::ItemPrice >(Arena* arena) {
  return Arena::CreateInternal< ::price::ItemPrice >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
