// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: price.proto
#ifndef GRPC_price_2eproto__INCLUDED
#define GRPC_price_2eproto__INCLUDED

#include "price.pb.h"

#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace price {

class Pricer final {
 public:
  static constexpr char const* service_full_name() {
    return "price.Pricer";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetPrice(::grpc::ClientContext* context, const ::price::ItemID& request, ::price::ItemPrice* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::price::ItemPrice>> AsyncGetPrice(::grpc::ClientContext* context, const ::price::ItemID& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::price::ItemPrice>>(AsyncGetPriceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::price::ItemPrice>> PrepareAsyncGetPrice(::grpc::ClientContext* context, const ::price::ItemID& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::price::ItemPrice>>(PrepareAsyncGetPriceRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::price::ItemPrice>* AsyncGetPriceRaw(::grpc::ClientContext* context, const ::price::ItemID& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::price::ItemPrice>* PrepareAsyncGetPriceRaw(::grpc::ClientContext* context, const ::price::ItemID& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status GetPrice(::grpc::ClientContext* context, const ::price::ItemID& request, ::price::ItemPrice* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::price::ItemPrice>> AsyncGetPrice(::grpc::ClientContext* context, const ::price::ItemID& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::price::ItemPrice>>(AsyncGetPriceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::price::ItemPrice>> PrepareAsyncGetPrice(::grpc::ClientContext* context, const ::price::ItemID& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::price::ItemPrice>>(PrepareAsyncGetPriceRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::price::ItemPrice>* AsyncGetPriceRaw(::grpc::ClientContext* context, const ::price::ItemID& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::price::ItemPrice>* PrepareAsyncGetPriceRaw(::grpc::ClientContext* context, const ::price::ItemID& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetPrice_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetPrice(::grpc::ServerContext* context, const ::price::ItemID* request, ::price::ItemPrice* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetPrice : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_GetPrice() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetPrice() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPrice(::grpc::ServerContext* context, const ::price::ItemID* request, ::price::ItemPrice* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetPrice(::grpc::ServerContext* context, ::price::ItemID* request, ::grpc::ServerAsyncResponseWriter< ::price::ItemPrice>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetPrice<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_GetPrice : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_GetPrice() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetPrice() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPrice(::grpc::ServerContext* context, const ::price::ItemID* request, ::price::ItemPrice* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetPrice : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_GetPrice() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetPrice() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetPrice(::grpc::ServerContext* context, const ::price::ItemID* request, ::price::ItemPrice* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetPrice(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetPrice : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_GetPrice() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::price::ItemID, ::price::ItemPrice>(std::bind(&WithStreamedUnaryMethod_GetPrice<BaseClass>::StreamedGetPrice, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_GetPrice() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetPrice(::grpc::ServerContext* context, const ::price::ItemID* request, ::price::ItemPrice* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetPrice(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::price::ItemID,::price::ItemPrice>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetPrice<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetPrice<Service > StreamedService;
};

}  // namespace price


#endif  // GRPC_price_2eproto__INCLUDED
