// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: price.proto

#include "price.pb.h"
#include "price.grpc.pb.h"

#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace price {

static const char* Pricer_method_names[] = {
  "/price.Pricer/GetPrice",
};

std::unique_ptr< Pricer::Stub> Pricer::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Pricer::Stub> stub(new Pricer::Stub(channel));
  return stub;
}

Pricer::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_GetPrice_(Pricer_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Pricer::Stub::GetPrice(::grpc::ClientContext* context, const ::price::ItemID& request, ::price::ItemPrice* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetPrice_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::price::ItemPrice>* Pricer::Stub::AsyncGetPriceRaw(::grpc::ClientContext* context, const ::price::ItemID& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::price::ItemPrice>::Create(channel_.get(), cq, rpcmethod_GetPrice_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::price::ItemPrice>* Pricer::Stub::PrepareAsyncGetPriceRaw(::grpc::ClientContext* context, const ::price::ItemID& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::price::ItemPrice>::Create(channel_.get(), cq, rpcmethod_GetPrice_, context, request, false);
}

Pricer::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Pricer_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Pricer::Service, ::price::ItemID, ::price::ItemPrice>(
          std::mem_fn(&Pricer::Service::GetPrice), this)));
}

Pricer::Service::~Service() {
}

::grpc::Status Pricer::Service::GetPrice(::grpc::ServerContext* context, const ::price::ItemID* request, ::price::ItemPrice* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace price

